name: bloc_pattern
description: bloc 패턴 사용해보기

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
